config/routes.rb
Rails.application.routes.draw do
  get 'blood_glucoses/show'
  mount ActionCable.server => '/cable'

  resources :users
  resources :welcomes
  resources :change_user_password
  root 'welcomes#new'

  resources :reports do
    collection do
      get 'daily_reports'
      post 'daily_reports'
      get 'monthly_reports'
      post 'monthly_reports'
      get 'date_wise_reports'
      post 'date_wise_reports'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_glucose.rb
class BloodGlucose < ApplicationRecord
  belongs_to :user
  after_create_commit { MessageBroadcastJob.perform_later self }

  validates :level, presence: true
  validates :level, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 220 }, :allow_nil => true
  validates :check_up_date, presence: true
  validate :validate_daily_limit_exceeds, on: :create

  def validate_daily_limit_exceeds
    errors.add(:level, 'Daily limit exceeds') if total_reading >= 4
  end

  private

  def total_reading
    self.user = User.current
    user.present? && check_up_date.present? ? user.blood_glucoses.where(check_up_date: check_up_date.beginning_of_day..check_up_date.end_of_day).count : 0
  end
end

app/models/sign_in.rb
class SignIn < ActiveType::Object
  attribute :email, :string
  attribute :password, :string
  validate :validate_user_exists
  validate :validate_password_correct

  def user
    User.find_by(['email=? or username=?', email, email]) if email.present?
  end

  private

  def validate_user_exists
    errors.add(:user_id, 'not found') if user.blank?
  end

  def validate_password_correct
    if user && !user.authenticate(password)
      errors.add(:password, 'Incorrect password')
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blood_glucoses
  has_secure_password
  cattr_accessor :current

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'Invalid format' },
                    uniqueness: true
end

app/models/user/as_changepassword.rb
class User::AsChangepassword < ActiveType::Record[User]
  attribute :old_password
  before_save :validate_old_password_correct

  private

  def validate_old_password_correct
    errors.add(:old_password, 'Incorrect') unless authenticate(old_password)
  end
end

app/models/user/as_sign_up.rb
class User::AsSignUp < ActiveType::Record[User]
  attribute :password
  attribute :password_confirmation
  validates :password, presence: true, confirmation: true
  validates :terms, acceptance: true
end

app/models/user/patient.rb
class User::Patient < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_current_user

  def login_required
    if session[:user_id]
      return true
    else
      flash[:notice] = 'Please login to continue'
      session[:return_to] = request.url
      redirect_to controller: :welcomes, action: :new
      return false
    end
  end

  def current_user
    User.find session[:user_id] if session[:user_id]
  end

  private

  def set_current_user
    User.current = current_user
    end
end

app/controllers/blood_glucoses_controller.rb
class BloodGlucosesController < ApplicationController
  def show
    date = (params[:date] && params[:date].to_date) || Date.today
    @blood_glucoses = BloodGlucose.where(check_up_date: date.beginning_of_day..date.end_of_day)
  end
end

app/controllers/change_user_password_controller.rb
class ChangeUserPasswordController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to blood_glucoses_show_path, notice: 'password successfully changed.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User::AsChangepassword.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.fetch(:user, {}).permit(:old_password, :password, :password_confirmation)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_up_blood_glucose_report, except: [:monthly_reports]

  def daily_reports
    @reports = @report.daily_report
  end

  def monthly_reports
    if date_params.present?
      @report = BloodGlucoseReport.new(start_date: '1-' + date_params[:start_date])
    else
      @report = BloodGlucoseReport.new
    end
    @reports = @report.monthly_report
  end

  def date_wise_reports
    @reports = @report.date_wise_report
  end

  private

  def date_params
    params.fetch(:date, {}).permit(:start_date, :end_date)
  end

  def set_up_blood_glucose_report
    @report = BloodGlucoseReport.new(date_params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
layout :false

  def new
    @user = User::Patient.new
  end

  def create
    @user = User::Patient.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.reload.id
        format.html { redirect_to blood_glucoses_show_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.fetch(:user_patient, {}).permit(:full_name, :email, :username, :password, :password_confirmation)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout false, except: [:index]
  before_action :login_required, except: [:new, :create]
  def new
    build_sign_in
    redirect_to blood_glucoses_show_path if session[:user_id]
  end

  def create
    build_sign_in

    if @sign_in.save
      session[:user_id] = @sign_in.user.id
      redirect_to blood_glucoses_show_path
      flash[:success] = 'User was successfully signed in.'
    else
      flash[:danger] = 'Invalid credentials'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to action: 'new'
  end

  private

  def build_sign_in
    @sign_in = SignIn.new(sign_in_params)
  end

  def sign_in_params
    sign_in_params = params[:sign_in]
    sign_in_params.permit(:email, :password) if sign_in_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when :success
      'alert-success'
    when :danger
      'alert-danger'
    when :alert
      'alert-block'
    when :notice
      'alert-info'
    else
      flash_type.to_s
    end
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id]) # Use find_by_id to get nil instead of an error if user doesn't exist
   end
end

app/helpers/blood_glucoses_helper.rb
module BloodGlucosesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blood_glucoses/_blood_glucose.html.erb
<div class=blood-glucose>



<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <li class="list-group-item">
        <span class="label label-default label-pill pull-xs-right cursor-pointer delete_reading" id='<%=blood_glucose.id %>'>x</span>
        <%= blood_glucose.level %> mg/dl
      </li>
    </div>
  </div>
</div>
</div>

app/views/blood_glucoses/show.html.erb
<h1>Check up details</h1>
<div >
<ul id="reading" class="list-group">
  <%= render @blood_glucoses %>
</ul>
</div>




<form class="glucose-form">

    <fieldset class="form-group">
<label>Select Date</label>
      <div class="row">
        <div class="col-md-4"><input type="text" class="form-control" id="read_date" data-behaviour=datepicker ></div>

      </div>
</fieldset>
<fieldset class="form-group">
  <label>Enter Your Glucose Reading</label>
  <div class="row">
    <div class="col-md-4">
    <input type="text" id="glucose_level" class="form-control" data-behavior="glucose_reader">
  </div>
  </div>

</fieldset>
</form>


<script type="text/javascript">


$("#read_date").on("dp.change", function(e) {

            $.ajax({
              url:"/blood_glucoses/show",
              data: {date: e.target.value},
              dataType: "script"
            })
        });
</script>

app/views/blood_glucoses/show.js.erb
$('#reading').html("<%= j (render :partial=>@blood_glucoses) %>");

app/views/change_user_password/edit.html.erb
<%= form_for(@user, :url =>change_user_password_path(current_user.id),html:{ class: "form-signin"}) do |form| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<%end%>
<%= form.password_field :old_password,class: "form-control",required:true, placeholder:"Old Password" %>
<%= form.password_field :password,class: "form-control",required:true, placeholder:"New Password" %>
<%= form.password_field :password_confirmation,class: "form-control",required:true, placeholder:"Confirm Password" %>
<%= form.submit 'update',:class=>"btn btn-lg btn-primary btn-block btn-signin" %>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body class="home">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
              <div class="logo">

              </div>
                <div class="navi">
                    <ul>
                        <li class="active"><a href="/blood_glucoses/show"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li><a href="/reports/daily_reports"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Daily Report</span></a></li>
                        <li><a href="/reports/monthly_reports"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Monthly Report</span></a></li>
                        <li><a href="/reports/date_wise_reports"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Custom Report</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">

                                </div>
                            </nav>

                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">
                                    <li class="dropdown"><%=current_user.full_name%>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                          </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <div class="navbar-content">
                                                    <%= link_to ' Sign out', welcome_path( current_user.id ), :method => :delete %>
                                                      <div class="divider">
                                                      </div>
                                                    <%= link_to 'change password', edit_change_user_password_path( current_user.id ) %>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>
                <div class="user-dashboard">
                  <%= flash_messages %>
                  <%= yield %>

                </div>
            </div>
        </div>

    </div>

</body>
</html>

app/views/reports/_reports.html.erb
<p><label>  minimal level</label> : <%=@report.min_value.to_f%></p>
<p><label>  average level</label> : <%=@report.avg_value.to_f%></p>
<p><label>  maximum level</label> : <%=@report.max_value.to_f%></p>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>Patient Name</th>
      <th>Glucose Level</th>
      <th>Read at</th>
    </tr>
  </thead>
  <tbody>
<% @reports.each_with_index do |report,i| %>
<%i+=1%>
    <tr>
      <th scope="row"><%=i%></th>
      <td><%=report.patient_name%></td>
      <td><%=report.level%></td>
      <td><%=report.check_up_date%></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/reports/daily_reports.html.erb
<%=form_for :date,:url=>{:controller=>:reports,:action=>:daily_reports},:remote=>true,:html=>{class: 'form-inline'} do |f|%>
<div class="form-group">
  <label for="exampleInputName2">Select Date</label>
<input type="text" name="date[start_date]" class="form-control" data-behaviour=datepicker>
</div>
<%= f.submit "Go",:class=>"btn btn-primary"%>
<%end%>


<div style="margin-top:20px" id="reports">
<%= render :partial=>'reports'%>
<div>

app/views/reports/daily_reports.js.erb
$("#reports").html("<%= j (render :partial=>'reports') %>");

app/views/reports/date_wise_reports.html.erb
<%=form_for :date,:url=>{:controller=>:reports,:action=>:date_wise_reports},:remote=>true,:html=>{class: 'form-inline'} do |f|%>
<div class="form-group">
  <label for="exampleInputName2">Start Date</label>
<input type="text" name="date[start_date]" class="form-control" data-behaviour=datepicker>
<label for="exampleInputName2">End Date</label>
<input type="text" name="date[end_date]" class="form-control" data-behaviour=datepicker>
</div>
<%= f.submit "Go",:class=>"btn btn-primary"%>
<%end%>


<div style="margin-top:20px" id="reports">
<%= render :partial=>'reports'%>
<div>

app/views/reports/date_wise_reports.js.erb
$("#reports").html("<%= j (render :partial=>'reports') %>");

app/views/reports/monthly_reports.html.erb
<%=form_for :date,:url=>{:controller=>:reports,:action=>:monthly_reports},:remote=>true,:html=>{class: 'form-inline'} do |f|%>
<div class="form-group">
  <label for="exampleInputName2">Select Date</label>
<input type="text" name="date[start_date]" class="form-control" data-behaviour=monthpicker>
</div>
<%= f.submit "Go",:class=>"btn btn-primary"%>
<%end%>


<div style="margin-top:20px" id="reports">
<%= render :partial=>'reports'%>
<div>

app/views/reports/monthly_reports.js.erb
$("#reports").html("<%= j (render :partial=>'reports') %>");

app/views/users/_signup.html.erb
<%= bootstrap_form_for(@user, :url => users_path,html:{ class: "form-signin"}) do |form| %>
    <%= form.alert_message "Please fix the errors below." %>
    <%= form.text_field :full_name,class: "form-control",autofocus:true,required:true, placeholder:"Full Name" %>
    <%= form.text_field :email,class: "form-control",autofocus:true,required:true, placeholder:"Email address" %>
    <%= form.text_field :username,class: "form-control",autofocus:true,required:true, placeholder:"Username" %>

    <%= form.password_field :password,class: "form-control",required:true, placeholder:"Password" %>
      <%= form.password_field :password_confirmation,class: "form-control",required:true, placeholder:"Password" %>
  <div id="remember" class="checkbox">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <%= form.submit 'Sign Up',:class=>"btn btn-lg btn-primary btn-block btn-signin" %>

<%end%>
<div class="col-md-12 control">
  <div style="border-top: 1px solid#888; padding-bottom:15px; padding-top:15px; font-size:85%" >
      Already have an account!
<%=link_to "Sign in", new_welcome_path%>
        </div>
</div>

app/views/users/new.html.erb
<html>
 <head>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>
<body>

<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
    <div class="container">

        <div class="card card-container">
          <%=flash_messages%>
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="/assets/sweet.jpg" />
            <p id="profile-name" class="profile-name-card"></p>
<div id="signupbox">
<%= render :partial=>'signup' %>
</div>

        </div><!-- /card-container -->
    </div><!-- /container -->
</body>

</html>

app/views/welcomes/_signin.html.erb
<%= form_for(@sign_in, :url => welcomes_path,html:{ class: "form-signin"}) do |form| %>

    <span id="reauth-email" class="reauth-email"></span>
    <%= form.text_field :email,class: "form-control",id: "inputEmail",autofocus:true,required:true, placeholder:"Email address" %>

    <%= form.password_field :password,class: "form-control",required:true, placeholder:"Password" %>

    <%= form.submit 'Sign in',{:class=>"btn btn-lg btn-primary btn-block btn-signin",id: 'login'} %>

<%end%>
<div class="col-md-12 control">
  <div style="border-top: 1px solid#888; padding-bottom:15px; padding-top:15px; font-size:85%" >
      Don't have an account!
<%=link_to "Sign up here",new_user_path %>
        </div>
</div>

app/views/welcomes/_signup.html.erb
<%= form_for(:user, :url => users_path,html:{ class: "form-signin"}) do |form| %>

    <span id="reauth-email" class="reauth-email"></span>
    <%= form.text_field :full_name,class: "form-control",autofocus:true,required:true, placeholder:"Full Name" %>
    <%= form.text_field :email,class: "form-control",autofocus:true,required:true, placeholder:"Email address" %>
    <%= form.text_field :username,class: "form-control",autofocus:true,required:true, placeholder:"Username" %>

    <%= form.password_field :password,class: "form-control",required:true, placeholder:"Password" %>
      <%= form.password_field :password_confirmation,class: "form-control",required:true, placeholder:"Confirm Password" %>
  <div id="remember" class="checkbox">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <%= form.submit 'Sign Up',:class=>"btn btn-lg btn-primary btn-block btn-signin" %>

<%end%>
<div class="col-md-12 control">
  <div style="border-top: 1px solid#888; padding-bottom:15px; padding-top:15px; font-size:85%" >
      Already have an account!
          <a class="cursor-pointer" onClick="$('#signupbox').hide(); $('#signinbox').show()">
            Sign In Here
          </a>
        </div>
</div>

app/views/welcomes/new.html.erb
<html>
 <head>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>
<body>


    <div class="container">

        <div class="card card-container">
          <%=flash_messages%>
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="/assets/sweet.jpg" />
            <p id="profile-name" class="profile-name-card"></p>
             <div id="signinbox">
            <%= render :partial=>'signin' %>
          </div>

        </div><!-- /card-container -->
    </div><!-- /container -->
</body>

</html>